export const phonebookTypes = {
  FETCH_PHONEBOOK_LIST_START: "FETCH_PHONEBOOK_LIST_START",
  FETCH_PHONEBOOK_LIST_SUCCESS: "FETCH_PHONEBOOK_LIST_SUCCESS",
  FETCH_PHONEBOOK_LIST_FAILURE: "FETCH_PHONEBOOK_LIST_FAILURE",

  FETCH_ADD_PHONEBOOK_LIST_START: "FETCH_ADD_PHONEBOOK_LIST_START",
  FETCH_ADD_PHONEBOOK_LIST_SUCCESS: "FETCH_ADD_PHONEBOOK_LIST_SUCCESS",
  FETCH_ADD_PHONEBOOK_LIST_FAILURE: "FETCH_ADD_PHONEBOOK_LIST_FAILURE",

  // FETCH_REJECTED_JOB_START: "FETCH_REJECTED_JOB_START",
  // FETCH_REJECTED_JOB_SUCCESS: "FETCH_REJECTED_JOB_SUCCESS",
  // FETCH_REJECTED_JOB_FAILURE: "FETCH_REJECTED_JOB_FAILURE",
  // ADD_ACCEPTED_JOB_START: "ADD_ACCEPTED_JOB_START",
  // ADD_REJECTED_JOB_START: "ADD_REJECTED_JOB_START",
};
